# Makefile for a C++ project with unittest

# Compiler settings
CXX = g++
CXXFLAGS = -Wall
CXXFLAGS += -I"$(CPPUTEST_HOME)/include"
CXXFLAGS += -include "$(CPPUTEST_HOME)/include/CppUTest/MemoryLeakDetectorNewMacros.h"
CFLAGS += -include "$(CPPUTEST_HOME)/include/CppUTest/MemoryLeakDetectorMallocMacros.h"

LDFLAGS = -L"$(CPPUTEST_HOME)/lib"
LDLIBS = -lCppUTest -lCppUTestExt

# Target executable name
TARGET = unittest.exe

# Object files
OBJS = unittest.o fizzbuzz.o

# Build target
all: $(TARGET)

# Rule to link the program
$(TARGET): $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) -o $(TARGET) $(LDLIBS)

# Rule to compile the unittest source file
unittest.o: unittest.cpp fizzbuzz.h
	$(CXX) $(CXXFLAGS) -c unittest.cpp

# Rule to compile the fizzbuzz source file
fizzbuzz.o: fizzbuzz.c fizzbuzz.h
	$(CXX) $(CXXFLAGS) -c fizzbuzz.c

# Clean target
clean:
	del "*.o"
	del "*.exe"
